
const AppState = Object.freeze({
  LOADING: Symbol("LOADING"),
  ITEM_NOT_LINKED: Symbol("ITEM_NOT_LINKED"),
  ITEM_LINKED: Symbol("ITEM_LINKED"),
  PUBLIC_TOKEN_EXCHANGE_PENDING: Symbol("PUBLIC_TOKEN_EXCHANGE_PENDING"),
  PUBLIC_TOKEN_EXCHANGED: Symbol("PUBLIC_TOKEN_EXCHANGED"),
  TRANSACTIONS_RECEIVED: Symbol("PUBLIC_TOKEN_EXCHANGED")
});

export { AppState }